version: '3'
services:
  jekyll-serve:
    image: jekyll/jekyll:4.0
    container_name: portfolio
    volumes:
      - ".:/srv/jekyll"
    ports:
      - 4000:4000
    command: jekyll serve --force_polling --livereload --config _config.yml,_config.docker.yml --incremental
    environment:
            - JEKYLL_ENV=docker